# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fcca8db47151e29eda231c93624bcd1bdc86cb3a40fe45ef5dbbf16194d2a7b5cb0ca57d8998499278c992c8ea6fe862c98781de7a595c840a7a1e93b21c0621

test:
  secret_key_base: 2eeeda01baf07d2610d6dc12b09703256ff0409cec312972b536c4ce74fe10f60cbaf6370cc3f66e7f361b0f4edc8deda4b30c1d7769f6ebe2b7f57b8c62dc1b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
