# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1459de6d524715888a8dd8583d6d0e18adf8a664bc523074aaa58a2d85bc78d25acf101c4712c3f04be650c2e0499eeb437486ac603cf36d5485eb3f7206dbff

test:
  secret_key_base: fe0b038eea6a51b65aae558b7ba85d43279b918aea9da2e8b0796aa86bb6fca2325208f714b9f727234549fa0455f3c6dedbbda98cff16bba66f7ab20d5ac6a4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
